### ISSUE TITLE
Doesn't work with 0.9.2 connect_urls

### ISSUE THREAD

**Issue by pires** [nats-io/jnats#42]
Given the following server info:
```
INFO {"server_id":"s76hOxUCzhR2ngkcVYSPPV","version":"0.9.2","go":"go1.6.3","host":"0.0.0.0","port":4222,"auth_required":true,"ssl_required":true,"tls_required":true,"tls_verify":false,"max_payload":1048576,"connect_urls":["10.0.1.3:4222","[fe80::42:aff:fe00:103]:4222"]}
```

I get:
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
       	at java.lang.String.substring(String.java:1967)
       	at io.nats.client.ServerInfo.addKVPair(ServerInfo.java:63)
       	at io.nats.client.ServerInfo.<init>(ServerInfo.java:36)
       	at io.nats.client.ConnectionImpl.processInfo(ConnectionImpl.java:645)
       	at io.nats.client.ConnectionImpl.processExpectedInfo(ConnectionImpl.java:595)
       	at io.nats.client.ConnectionImpl.processConnectInit(ConnectionImpl.java:543)
       	at io.nats.client.ConnectionImpl.connect(ConnectionImpl.java:346)
       	at io.nats.client.ConnectionFactory.createConnection(ConnectionFactory.java:411)
       	at io.nats.client.ConnectionFactory.createConnection(ConnectionFactory.java:401)
```

This happens because JSON parsing in `ServerInfo` ctor is done _manually_ instead of using a JSON parser library, which would most probably prevent this.

**Comment by pires** [comment]
With `gnatsd` 0.8.1 it works alright.
Tests would pass because of a couple things:
1. Mosts tests mock server-info (use `TCPConnectionMock`)
2. Tests against local NATS server don't have `connected_urls` because it's a single server, right @kozlovic?

**Comment by mcqueary** [comment]
Good catch. Will add a fix (and a test) for this.

For anyone reading this later and pondering "why do they not use a JSON parser library?", we try our best to avoid any unnecessary dependencies, and we control the exact format of the INFO string (for now), so it still doesn't seem worth it. We will continue to hope that Java eventually includes JSON support. :)
