### ISSUE TITLE
Memory leak or logic error

### ISSUE THREAD

**Issue by chilly** [nats-io/jnats#66]
run nats client and limit memory. 

init connection:
```
ConnectionFactory cf = new ConnectionFactory();
        cf.setServers(servers);
        cf.setMaxReconnect(5);
        cf.setPingInterval(5000L);
        cf.setReconnectAllowed(true);
        cf.setReconnectWait(2000);
        cf.setNoRandomize(false);
        cf.setMaxPendingBytes(200 * 1024 * 1024);
        cf.setMaxPendingMsgs(200);
        Connection nc = cf.createConnection();
```

```
// sub topic
conn.subscribe(topic, queueName, handler);
```

```
//handler:
 public void onMessage(Message msg) {
        String str = new String(msg.getData());
          // do something
    }
```

run with jvm args:

```
java -jar -agentlib:jdwp=transport=dt_socket,address=9908,server=y,suspend=n -server -Xmx2g -Xms2g -Xmn256m -XX:PermSize=128m -Xss256k -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSCompactAtFullCollection -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:+PrintGCDateStamps -Xloggc:./logs/gc.log  target/tower.jar
```
after run a while:  20mins, the program throw the exception.

Memory leak or logic error ?

```
Exception in thread "readloop" java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
	at io.nats.client.Parser.parse(Parser.java:212)
	at io.nats.client.ConnectionImpl.readLoop(ConnectionImpl.java:1371)
	at io.nats.client.ConnectionImpl$7.run(ConnectionImpl.java:1164)
	at io.nats.client.ConnectionImpl$6.run(ConnectionImpl.java:1142)
Exception in thread "readloop" java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
	at io.nats.client.Parser.parse(Parser.java:212)
	at io.nats.client.ConnectionImpl.readLoop(ConnectionImpl.java:1371)
	at io.nats.client.ConnectionImpl$7.run(ConnectionImpl.java:1164)
	at io.nats.client.ConnectionImpl$6.run(ConnectionImpl.java:1142)
Exception in thread "readloop" java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
	at io.nats.client.Parser.parse(Parser.java:212)
	at io.nats.client.ConnectionImpl.readLoop(ConnectionImpl.java:1371)
	at io.nats.client.ConnectionImpl$7.run(ConnectionImpl.java:1164)
	at io.nats.client.ConnectionImpl$6.run(ConnectionImpl.java:1142)
Exception in thread "readloop" java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
	at io.nats.client.Parser.parse(Parser.java:212)
	at io.nats.client.ConnectionImpl.readLoop(ConnectionImpl.java:1371)
	at io.nats.client.ConnectionImpl$7.run(ConnectionImpl.java:1164)
	at io.nats.client.ConnectionImpl$6.run(ConnectionImpl.java:1142)
Exception in thread "readloop" java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
	at io.nats.client.Parser.parse(Parser.java:212)
	at io.nats.client.ConnectionImpl.readLoop(ConnectionImpl.java:1371)
	at io.nats.client.ConnectionImpl$7.run(ConnectionImpl.java:1164)
	at io.nats.client.ConnectionImpl$6.run(ConnectionImpl.java:1142)
Exception in thread "readloop" java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
	at io.nats.client.Parser.parse(Parser.java:212)
	at io.nats.client.ConnectionImpl.readLoop(ConnectionImpl.java:1371)
	at io.nats.client.ConnectionImpl$7.run(ConnectionImpl.java:1164)
	at io.nats.client.ConnectionImpl$6.run(ConnectionImpl.java:1142)
Exception in thread "readloop" java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
	at io.nats.client.Parser.parse(Parser.java:212)
	at io.nats.client.ConnectionImpl.readLoop(ConnectionImpl.java:1371)
	at io.nats.client.ConnectionImpl$7.run(ConnectionImpl.java:1164)
	at io.nats.client.ConnectionImpl$6.run(ConnectionImpl.java:1142)
Exception in thread "readloop" java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
	at io.nats.client.Parser.parse(Parser.java:212)
	at io.nats.client.ConnectionImpl.readLoop(ConnectionImpl.java:1371)
	at io.nats.client.ConnectionImpl$7.run(ConnectionImpl.java:1164)
	at io.nats.client.ConnectionImpl$6.run(ConnectionImpl.java:1142)
Exception in thread "readloop" java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
	at io.nats.client.Parser.parse(Parser.java:212)
	at io.nats.client.ConnectionImpl.readLoop(ConnectionImpl.java:1371)
	at io.nats.client.ConnectionImpl$7.run(ConnectionImpl.java:1164)
	at io.nats.client.ConnectionImpl$6.run(ConnectionImpl.java:1142)
```

**Comment by mcqueary** [comment]
Thanks for reporting this. We don't currently test with a buffer this large (200MB). I'll have a look. Hopefully it can be reproduced in < 20min :)

**Comment by mcqueary** [comment]
Looking at this and your other issue (#67), I think the root cause is likely that your publisher is overrunning your consumer, and you're seeing issues on both sides. This is not a memory leak. It is a logic or configuration issue or maybe both. The parser buffer that stores the incoming msg body is smaller than the msg body it's trying to store. That shouldn't happen. 

Can you show me a your publisher code?

**Comment by chilly** [comment]
the publisher is not in the program.  In java process only do subscribe. 
And I use telnet to access nats in the same time. The telnet messages are ok, but java program throws the exception.

**Comment by chilly** [comment]
set reconnection buffer size = 200*1024*1024 solve the problem.  But in #67 , outofbound exception appears once. And can not repro again. thanks. I close the issue.

**Comment by chilly** [comment]
2016-09-20 11:29:32,109 ERROR [pinger] io.nats.client.ConnectionImpl: I/O error during flush
java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at io.nats.client.ConnectionImpl.processOpError(ConnectionImpl.java:672)
        at io.nats.client.ConnectionImpl.processPingTimer(ConnectionImpl.java:1591)
        at io.nats.client.ConnectionImpl$11.run(ConnectionImpl.java:1559)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at io.nats.client.NATSThread.run(NATSThread.java:63)

sorry, it appears .  reopen it.
Exception in thread "readloop" java.nio.BufferOverflowException
        at java.nio.Buffer.nextPutIndex(Buffer.java:521)
        at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
        at io.nats.client.Parser.parse(Parser.java:212)
        at io.nats.client.ConnectionImpl.readLoop(ConnectionImpl.java:1371)
        at io.nats.client.ConnectionImpl$7.run(ConnectionImpl.java:1164)
        at io.nats.client.ConnectionImpl$6.run(ConnectionImpl.java:1142)

**Comment by chilly** [comment]
. maybe the reason is that nats is stop

**Comment by mcqueary** [comment]
@chilly `gnatsd` being stopped could defubuteky cause this: 

`2016-09-20 11:29:32,109 ERROR [pinger] io.nats.client.ConnectionImpl: I/O error during flush
java.net.SocketException: Broken pipe`

,,,but it would not cause the `BufferOverflowException` you're seeing on the subscriber side. If you can give me some runnable publisher/subscriber code that reproduces the problem(s), I cantry to help you further.
