### ISSUE TITLE
heap is not big enough ? 

### ISSUE THREAD

**Issue by chilly** [nats-io/jnats#67]
in 5.3.0 jnats

server 2g memory. and jvm use default heap size, maybe 256m.

then build 10 connections  and only publish datas. After running a while, it throws the exception.

java.io.IOException: nats: outbound buffer limit exceeded
	at io.nats.client.ConnectionImpl._publish(ConnectionImpl.java:1996)
	at io.nats.client.ConnectionImpl.publish(ConnectionImpl.java:2059)
	at io.nats.client.ConnectionImpl.publish(ConnectionImpl.java:2064)
	at com.paratera.towerTest.Main$X.lambda$run$0(Main.java:69)
	at com.paratera.towerTest.Main$X$$Lambda$1/1671537075.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.paratera.towerTest.Main$X.run(Main.java:65)
java.io.IOException: nats: outbound buffer limit exceeded
	at io.nats.client.ConnectionImpl._publish(ConnectionImpl.java:1996)
	at io.nats.client.ConnectionImpl.publish(ConnectionImpl.java:2059)
	at io.nats.client.ConnectionImpl.publish(ConnectionImpl.java:2064)
	at com.paratera.towerTest.Main$X.lambda$run$0(Main.java:69)

**Comment by mcqueary** [comment]
When your connection to the NATS server is unexpectedly dropped, the `Connection` object flushes any pending data to a buffer, and when/if the connection is reestablished, that buffer is flushed to the new connection. The error you received is because that reconnect buffer is set too small. Try calling `cf.setReconnectBufSize(2 * 1024 * 1024)` (or larger) and see if you still get this issue.

More interesting is why your connection is being dropped in the first place...

**Comment by mcqueary** [comment]
@chilly Chico, please try your test(s) with the latest snapshot if you get a chance.

**Comment by mcqueary** [comment]
As you suggested in #66, it appears your `gnatsd` is stopping. If you can provide a runnable test case and details, I'm happy to look into it further.
