### ISSUE TITLE
I found ArrayIndexOutOfBoundsException exception in jnats

### ISSUE THREAD

**Issue by chilly** [nats-io/jnats#70]
[EDIT: formatting]

```
java.lang.ArrayIndexOutOfBoundsException
	at io.nats.client.Message.<init>(Message.java:64)
	at io.nats.client.ConnectionImpl.processMsg(ConnectionImpl.java:1452)
	at io.nats.client.Parser.parse(Parser.java:229)
	at io.nats.client.ConnectionImpl.readLoop(ConnectionImpl.java:1371)
	at io.nats.client.ConnectionImpl$7.run(ConnectionImpl.java:1164)
	at io.nats.client.ConnectionImpl$6.run(ConnectionImpl.java:1142)
buf.length=65536, offset=0, data.length=7704, length=7705
``` 

Exception throws here:
```
try {
    System.arraycopy(buf, offset, data, 0, length);  // here
} catch (ArrayIndexOutOfBoundsException e) {
    System.err.printf("buf.length=%d, offset=%d, data.length=%d, length=%d\n, buf=[%s]",
        buf.length, offset, data.length, length, new String(buf, offset, length));
     e.printStackTrace();
}
```
data.length=7704 but want copy 0-7705 ?

the buffer here:
```
buf=[20160908153544 {"cluster":"abcabcee","nfsd":{"readbytes":0.00,"writebytes":0.00},"nfs0":{"server":"10.24.171.90","vers":"4","serverpoint0":"/mnt/YWFZ1/share/YWFZ1","mountpoint0":"/hongshan1","serverpoint1":"/mnt/YWFZ2/share/YWFZ2","mountpoint1":"/hongshan2","events":{"inoderevalidate":0.0,"dentryrevalidate":0.0,"datainvalidate":0.0,"attrinvalidate":0.0,"vfsopen":0.0,"vfslookup":0.0,"vfsaccess":0.0,"vfsupdatepage":0.0,"vfsreadpage":0.0,"vfsreadpages":0.0,"vfswritepage":0.0,"vfswritepages":0.0,"vfsgetdents":0.0,"vfssetattr":0.0,"vfsflush":0.0,"vfsfsync":0.0,"vfslock":0.0,"vfsrelease":0.0,"congestionwait":0.0,"setattrtrunc":0.0,"extendwrite":0.0,"sillyrename":0.0,"shortread":0.0,"shortwrite":0.0,"delay":0.0,"pnfs_read":0.0,"pnfs_write":0.0},"bytes":{"normalreadbytes":0.0,"normalwritebytes":0.0,"directreadbytes":0.0,"directwritebytes":0.0,"serverreadbytes":0.0,"serverwritebytes":0.0,"readpages":0.0,"writepages":0.0},"rpc":{"null":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queuemeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"destroy_session":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"sequence":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"get_lease_time":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"reclaim_complete":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"layoutget":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"getdeviceinfo":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"layoutcommit":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"layoutreturn":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"secinfo_no_name":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"test_stateid":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"free_stateid":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"getdevicelist":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"bind_conn_to_session":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"destroy_clientid":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0}}},"nfs_all_in":0,"nfs_all_out":0,"nfs_page_in":0,"nfs_page_out":0,"nfs_pkg_in":0,"nfs_pkg_out":0,"hostname":"node1608","ip":"10.24.173.135","timestamp":1474573351647,"hostid":"8A431260-1DAC-11E5-96CC-199F18968E279943"}
**MSG abcabcee.load.nfs 1 7704**
20160908153544 {"cluster":"abcabcee","nfsd":{"readbytes":0.00,"writebytes":0.00},"nfs0":{"server":"10.24.171.90","vers":"4","serverpoint0":"/mnt/YWFZ1/share/YWFZ1","mountpoint0":"/hongshan1","serverpoint1":"/mnt/YWFZ2/share/YWFZ2","mountpoint1":"/hongshan2","events":{"inoderevalidate":0.0,"dentryrevalidate":0.0,"datainvalidate":0.0,"attrinvalidate":0.0,"vfsopen":0.0,"vfslookup":0.0,"vfsaccess":0.0,"vfsupdatepage":0.0,"vfsreadpage":0.0,"vfsreadpages":0.0,"vfswritepage":0.0,"vfswritepages":0.0,"vfsgetdents":0.0,"vfssetattr":0.0,"vfsflush":0.0,"vfsfsync":0.0,"vfslock":0.0,"vfsrelease":0.0,"congestionwait":0.0,"setattrtrunc":0.0,"extendwrite":0.0,"sillyrename":0.0,"shortread":0.0,"shortwrite":0.0,"delay":0.0,"pnfs_read":0.0,"pnfs_write":0.0},"bytes":{"normalreadbytes":0.0,"normalwritebytes":0.0,"directreadbytes":0.0,"directwritebytes":0.0,"serverreadbytes":0.0,"serverwritebytes":0.0,"readpages":0.0,"writepages":0.0},"rpc":{"null":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"read":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"write":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"commit":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"open":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"open_confirm":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"open_noattr":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"open_downgrade":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"close":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"setattr":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"fsinfo":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"renew":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"setclientid":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"setclientid_confirm":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"lock":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"lockt":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"locku":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"access":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"getattr":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"lookup":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"lookupp":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"remove":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"rename":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"link":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"symlink":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"create":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"pathconf":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"statfs":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"readlink":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"readdir":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":0.0,"bytes_recv":0.0,"queue":0.0,"rtt":0.0,"execute":0.0},"server_caps":{"ops":0.0,"trans":0.0,"timeouts":0.0,"bytes_sent":u.0,"b0y.t0,"_retes_s0e.n0t,""]
```

**Comment by mcqueary** [comment]
Good catch -- thank you!

**Comment by mcqueary** [comment]
@chilly Besides the OOBE problem, there appears to be a parsing problem here. In your output, `buf` contains the last half of one message, and the first half of the next one. That would be OK, if `offset` marked the beginning of a message body, but it doesn't. 

Can you reproduce this problem every time? If so, can you give me an [MCVE] (http://stackoverflow.com/help/mcve) that demonstrates it? 

Thanks in advance!

**Comment by mcqueary** [comment]
It would also be useful to know what charset encoding you are using.

**Comment by chilly** [comment]
ascii only.  I have already write correct simple nats java client for the parser. In your code, multi-thread will throws the exception. I tried to lock the parse part, but failed. So I write my own parse. I paste here.  The solution is very different with your code. And I Hope you will get my idea.
 
only one thread  call loop(). And only one thread call in.read() method. 

If you want use multi-thread for speeding up parsing, you can use SUB queue command.

> 

public void loop() {
        while (true) {
            try {

                int tmp = -1;
                Status s = new Status();
                Topic msgTopic = new Topic();
                while (( tmp = in.read() ) != -1) {
                    // MSG
                    char c = (char) tmp;
                    if (!s.isEnd() && !s.update(c)) {  // update call for state machine
                        continue;
                    }
                    
                    // PING
                    if (s.isPing()) {
                        NatsThreadPool.submit(new Runnable() {
                            @Override
                            public void run() {
                                doPong();
                            }
                        });
                        s.clean();
                        continue;
                    }

                    if (!msgTopic.isTopicEnd() && !msgTopic.update(c)) {  // update call for state machine
                        continue;
                    }

                    byte[] b = new byte[msgTopic.getLength()];
                    b[0] = (byte) c;
                    int off = 1;
                    int len = b.length - 1;
                    int l = 0;
                    while (( l = in.read(b, off, len) ) != -1) {
                        off += l;
                        len -= l;
                        if (len == 0) {
                            break;
                        }
                    }
                    if (len == 0) {
                        final String subject = msgTopic.getTopic();
                        final String mysid = msgTopic.getSid();
                        final int length = msgTopic.getLength();
                        NatsThreadPool.submit(new Runnable() {
                            @Override
                            public void run() {
                                handler.process(new Msg(subject, mysid, length, b));
                            }
                        });
                    } 
                    msgTopic = new Topic();
                    s.clean();
                }
            } catch (IOException e) {
                logger.warn("some io error.", e);
                if (!reConnect()) {
                    return;
                }
            } catch(Exception e) {
                logger.warn("some error",e);
            }
        }
    }

**Comment by mcqueary** [comment]
Apologies, but I do not understand what you are saying, especially the 'your code'/'my code' part. Is the problem you initially reported above something that occurred while running a client that is using the public interfaces of the `jnats` client contained in this repository?

The particular piece that is confusing me is your mention of multi-threaded access. Although `jnats` supports multi-threaded clients, each `Connection` has a single read loop thread, which reads from a single socket connection, and executes the `Parser` to create `Message` objects that are then distributed to (processed by) a `Subscription`. 

Can you give me a simple `jnats` client publisher and subscriber (based on the implementation and public interfaces contained in this repo) that will reproduce (even sometimes) the exception you reported above?

Thanks in advance.
